image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - mvn_build
  - docker_build
  - deploy

maven-build:
  image: maven:3-jdk-8
  stage: mvn_build
  cache:
    paths:
      - .m2/repository
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  script: mvn -Dmaven.test.skip=true package sonar:sonar -Dsonar.host.url="http://54.175.45.71:9000" -B
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: docker_build
  script:
    - docker login registry.gitlab.com -u $GITLAB_USER -p $GITLAB_PWD
    - docker build -t registry.gitlab.com/santanudey/account .
    - docker push registry.gitlab.com/santanudey/account

deploy_live:
  stage: deploy
  environment:
    name: live
    url: https:/lkq-vmn.com
  cache:
    paths:
      - binary-cache
  before_script:
    - apk add --no-cache curl ca-certificates
    # create the binary-cache folder if not present
    - test -d binary-cache || mkdir binary-cache
    # install kubectl binary into binary-cache if not already present
    - test -f binary-cache/kubectl || curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.7.2/bin/linux/amd64/kubectl
    - test -f binary-cache/kubectl || mv kubectl binary-cache/kubectl
    # install kubectl binary into /usr/local/bin if not already present
    - test -f /usr/local/bin/kubectl || install -m 770 binary-cache/kubectl /usr/local/bin
    # ... other stuff ...
  script:
    - kubectl version
    - kubectl set image deployment nginx nginx=nginx:1.11.5 --record

    