image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - build
  - package

maven-build:
  image: maven:3-jdk-8
  stage: build
  cache:
    paths:
      - .m2/repository
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  script: mvn -Dmaven.test.skip=true package sonar:sonar -Dsonar.host.url="http://54.175.45.71:9000" -B
  artifacts:
    paths:
      - target/*.jar

docker-build:
  stage: package
  script:
    - docker login registry.gitlab.com -u santanudey -p nabinDE@1
    - docker build -t registry.gitlab.com/santanudey/account .
    - docker push registry.gitlab.com/santanudey/account