image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - deploy

deploy_live:
  image: lachlanevenson/k8s-kubectl:latest
  stage: deploy
  environment:
    name: live
    url: https:/lkq-vmn.com
  script:
    - kubectl version
    - kubectl set image deployment nginx nginx=nginx:1.11.5 --record