image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - maven_package
  - docker_build
  - deploy_dev

maven_package:
  image: maven:3-jdk-8
  stage: maven_package
  cache:
    paths:
      - .m2/repository
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  script: mvn -Dmaven.test.skip=true package sonar:sonar -Dsonar.host.url="http://54.175.45.71:9000" -B
  artifacts:
    paths:
      - target/*.jar

docker_build:
  stage: docker_build
  script:
    - docker login registry.gitlab.com -u $GITLAB_USER -p $GITLAB_PWD
    - docker build -t registry.gitlab.com/santanudey/account .
    - docker push registry.gitlab.com/santanudey/account

deploy_dev:
  stage: deploy_dev
  environment:
    name: dev
    url: https:/lkqvmn-dev.com
  script:
    - hostname
    - kubectl version
    - kubectl config get-contexts
    - kubectl create -f /home/ec2-user/deployments/accountserv_depl_service.yaml 

    