image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay

stages:
  - maven_package
  - docker_build
  - deploy_DEV
  - deploy_SIT

maven_package:
  image: maven:3-jdk-8
  stage: maven_package
  cache:
    paths:
      - .m2/repository
  variables:
    MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  script: mvn -Dmaven.test.skip=true package sonar:sonar -Dsonar.host.url="http://52.204.209.193:9000" -B
  artifacts:
    paths:
      - target/*.jar

docker_build:
  stage: docker_build
  script:
    - docker login registry.gitlab.com -u $GITLAB_USER -p $GITLAB_PWD
    - docker build -t registry.gitlab.com/santanudey/account:v1.0 .
    - docker push registry.gitlab.com/santanudey/account

deploy_dev:
  stage: deploy_DEV
  environment:
    name: dev
    url: https:/lkqvmn-dev.com
  script:
    - kubectl apply -f /home/ec2-user/deployments/accountserv_depl_service_dev.yaml 
    - kubectl get pod --namespace=lkq-dev
    - kubectl get svc --namespace=lkq-dev

deploy_sit:
  stage: deploy_SIT
  environment:
    name: sit
    url: https:/lkqvmn-sit.com
  script:
    - kubectl apply -f /home/ec2-user/deployments/accountserv_depl_service_sit.yaml
    - kubectl get pod --namespace=lkq-sit
    - kubectl get svc --namespace=lkq-sit
  when: manual

    